[KAN-236] User Entity 설계
diningBuddy/be pull request #7
Opened 2024-10-22 14:07 UTC by Ting97ok

2024-10-26 07:05 UTC, sinkyoungdeok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var socialUserList: MutableList<SocialUser> = mutableListOf()
자료형(List)는 네이밍에 안넣는게 좋을 것 같아요.
나중에 Set으로 바뀌게되면 네이밍도 바껴야 될수도 있으니~

2024-10-26 07:05 UTC, sinkyoungdeok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/SocialUser.kt
> +    val user: User
이쪽에서 user가 필요한일이 있을까여? 우선 지우고 나중에 필요할때 추가하면 어떨까요?

2024-10-26 12:59 UTC, Ting97ok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var socialUserList: MutableList<SocialUser> = mutableListOf()
수정되었습니다 !

2024-10-26 12:59 UTC, Ting97ok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/SocialUser.kt
> +    val user: User
[오프라인 회의로 해결]
단방향 OneToMany의 단점으로 인해 현상 유지

2024-10-26 15:05 UTC, sinkyoungdeok requested changes

2024-10-26 15:05 UTC, sinkyoungdeok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var phoneNumber: String = "",
= "" 으로 기본 값을 세팅해야할지는 고민한번씩 필요합니다. 

우선 phoneNumber는 필수값으로 넘겨받아야하기때문에 ""로 세팅하는것이아닌 파라미터로 반드시 넘어와야할 것 같아요.

2024-10-28 12:53 UTC, Ting97ok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var phoneNumber: String = "",
기존에 이런 방식으로 되어 있길래 관례 처럼 하고 있는 줄 알았습니다..ㅎ 
초기화에 초점을 두는게 아니라 실제 해당 값의 nullable을 기준으로 작성하면 될까요 ?

2024-10-28 12:55 UTC, sinkyoungdeok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var phoneNumber: String = "",
nullable이랑은 다른개념이에여 
= "" 로 세팅해두는건 기본값을 세팅해두는거에요~ 
파라미터로 반드시 받아야하는것들은 기본값 세팅없이 해야합니다.

2024-10-28 13:00 UTC, Ting97ok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var phoneNumber: String = "",
아 설명이 부족했던 것 같습니다
기존에 = "" 로 초기화한 내용이 null 값 허용 안한다는 걸 명시적으로 보여주고 싶었나해서 저렇게 이야기가 나왔네여..ㅎ
초기화는 진짜 필요한 예를들어 withdrawal = fasle와 같은 내용 제외하고
상황에 맞게 수정하겠습니다.

2024-10-29 13:49 UTC, sinkyoungdeok approved these changes
댓글남겨놓은거 한번 고민해서 머지해주세요 ~

2024-10-29 13:49 UTC, sinkyoungdeok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var isTermsAgreed: Boolean = false,
얘도 기본값 세팅 안해도 되지 않을까여?

2024-10-29 13:54 UTC, Ting97ok commented on src/main/kotlin/com/restaurant/be/user/domain/entity/User.kt
> +    var isTermsAgreed: Boolean = false,
음.. 그러네여 수정하고 머지 하겠습니다

2024-11-01 16:24 UTC, merged